config/routes.rb
Stui::Application.routes.draw do

  root to: 'pages#home'
  match 'about_us' => 'pages#about_us'

  match 'photos' => 'pioneers#photos'
  match 'vectors' => 'pioneers#vectors'
  match 'illustrations' => 'pioneers#illustrations'
  match 'statistics' => 'pioneers#statistics'

  match 'pioneers/:id/vote_up' => 'pioneers#vote_up', :as => :vote_up
  match 'pioneers/:id/vote_down' => 'pioneers#vote_down', :as => :vote_down

  resources :pioneers

  resources :articles do
    resources :comments
  end

  devise_for :users
  resources :users do
    member do
      put :update_pass
      put :change_article_notification
      put :change_timezone
    end
  end

  match 'admin' => redirect('/admin/users')
  namespace :admin do
    resources :users
    resources :articles
    resources :pioneers
    resources :pendings
  end

end

app/models/article.rb
class Article
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  embeds_many :comments

  scope :published, where(published: true)
  scope :sorted_by_created_at, order_by(created_at: -1)
  scope :published_sorted_by_created_at, published.sorted_by_created_at


  attr_accessible :title, :text, :published

  field :title,             type: String, default: ""
  field :text,              type: String, default: ""
  field :user_name,         type: String, default: ""
  field :published,         type: Boolean, default: false
  field :submitted,         type: Boolean, default: false

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController

  def index
    @title = "Blog"
    @articles = Article.sorted_by_created_at.paginate(page: params[:page], per_page: 10)
    authorize! :index, @articles
  end

  def show
    @article = Article.find(params[:id])
    @title = @article.title
    authorize! :show, @article
  end

  def new
    @title = "New article"
    @article = Article.new
    authorize! :create, @article
  end

  def edit
    @title = 'Edit article'
    @article = Article.find(params[:id])
    authorize! :edit, @article
  end

  def create
    @article = current_user.articles.new(params[:article])
    @article.user_name = current_user.name
    authorize! :create, @article
    if @article.save
      redirect_to(admin_articles_url,
                  notice: 'Article was successfully created.')
    else
      render action: "new"
    end
  end

  def update
    @article = Article.find(params[:id])
    authorize! :edit, @article
    if @article.update_attributes(params[:article])
      redirect_to([:admin, @article], notice: 'Article was successfully updated.')
    else
      render action: "edit"
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article
    @article.destroy
    redirect_to(admin_articles_url)
  end

end

app/controllers/articles_controller.rb
 class ArticlesController < ApplicationController

  def index
    @title = t(:blog_h)
    @articles = Article.published_sorted_by_created_at.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = Article.find(params[:id])
    @title = @article.title
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_article.html.erb
<div>
  <h3><%= article.title %></h3>
  <p class="muted">
	<%= article.created_at.to_s(:user_datetime) %> |
	<%= link_to "Comments: #{article.comments.count}", article_path(article, anchor: "comments") %>
	| <% if article.published? %>Published<% else %>Unpublished<% end %>
	| <%= link_to 'Edit', edit_admin_article_path(article) %>
	| <%= link_to 'Delete', [:admin, article], confirm: 'Are you sure?', method: :delete %>
  </p>
  <div><%= raw(article.text) %></div>
</div>

app/views/admin/articles/_comment_tr.html.erb
<tr>
  <td>
	<p class="muted">by <%= comment.user_name %>
	  | <%= comment.created_at.to_s(:user_datetime) %>
	  | <%= link_to 'Delete', article_comment_path(@article, comment),
			confirm: 'Are you sure?', method: :delete %>
	</p>
	<p><%= comment.content %></p>
  </td>
</tr>

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <fieldset>

  <legend><%= @title %></legend>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :text %>
    <%= f.text_area :text, rows: 17, style: "width: 800px" %>

    <label class="checkbox">
	  <%= f.check_box :published %> Published
    </label>
    <button type="submit" class="btn">Save</button>

  </fieldset>

<% end %>

app/views/admin/articles/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/admin/articles/index.html.erb
<h3>
  Articles (<%= Article.count %>)
</h3>

<% if @articles.length > 0 %>

<table class="table table-striped table-condensed">
<% @articles.each do |article| %>
  <tr>
	<td style="width:350px;">
	  <%= link_to article.title, admin_article_path(article) %>
	</td>
	<td>
	  <%= article.user_name %>
	</td>
	<td>
	  <% if article.published? %>
	    published
	  <% else %>
	    hidden
	  <% end %>
	</td>
	<td>
	  <%= article.created_at.to_s(:short_datetime) %>
	</td>
  </tr>
<% end %>
</table>

<%= will_paginate %>

<% else %>

<p>There are no any articles.</p>

<% end %>

app/views/admin/articles/new.html.erb
<%= render 'form' %>

app/views/admin/articles/show.html.erb
<%= render 'article', article: @article %>

<h4>Comments</h4>
<%= content_tag(:a, '', name: 'comments') %>
<table id="comments-table" class="table table-striped">
  <% @article.comments.each do |comment| %>
    <%= render 'comment_tr', comment: comment %>
  <% end %>
</table>

<h4>New Comment</h4>
<%= form_for [@article, Comment.new], remote: true do |f| %>
  <fieldset>
  <p><%= f.text_area :content, rows: 4, style: 'width: 600px' %></p>
  <%= f.submit 'Create comment', class: 'btn' %>
  </fieldset>
<% end %>