config/routes.rb
Stui::Application.routes.draw do

  root to: 'pages#home'
  match 'about_us' => 'pages#about_us'

  match 'photos' => 'pioneers#photos'
  match 'vectors' => 'pioneers#vectors'
  match 'illustrations' => 'pioneers#illustrations'
  match 'statistics' => 'pioneers#statistics'

  match 'pioneers/:id/vote_up' => 'pioneers#vote_up', :as => :vote_up
  match 'pioneers/:id/vote_down' => 'pioneers#vote_down', :as => :vote_down

  resources :pioneers

  resources :articles do
    resources :comments
  end

  devise_for :users
  resources :users do
    member do
      put :update_pass
      put :change_article_notification
      put :change_timezone
    end
  end

  match 'admin' => redirect('/admin/users')
  namespace :admin do
    resources :users
    resources :articles
    resources :pioneers
    resources :pendings
  end

end

app/models/pioneer.rb
class Pioneer
  include Mongoid::Document
  include Mongo::Voteable
  include Mongoid::Timestamps

  IDLAST_USER_NAME = 'IDLast.com'

  before_save :mask_id
  belongs_to :user

  scope :pending, where(approved: false)
  scope :approved, where(approved: true)
  scope :sorted_by_img_id, order_by(img_id: -1)

  scope :approved_sorted_by_img_id, approved.sorted_by_img_id

  scope :vectors, where(type: 'vector')
  scope :approved_vectors, vectors.approved
  scope :approved_vectors_sorted_by_img_id, approved_vectors.sorted_by_img_id

  scope :illustrations, where(type: 'illustration')
  scope :approved_illustrations, illustrations.approved
  scope :approved_illustrations_sorted_by_img_id, approved_illustrations.sorted_by_img_id

  scope :photos, where(type: 'photo')
  scope :approved_photos, photos.approved
  scope :approved_photos_sorted_by_img_id, approved_photos.sorted_by_img_id

  scope :of_type, ->(type){ where(type: type) }
  scope :approved_of_type, ->(type){ approved.of_type(type) }
  scope :approved_of_type_sorted_by_img_id, ->(type){ of_type(type).approved_sorted_by_img_id }
  scope :pendings_of_type, ->(type){ pending.of_type(type) }
  scope :last_approved_of_type, ->(type){ approved_sorted_by_img_id.of_type(type).limit(1) }

  scope :of_user, ->(user_id){ where(user_id: user_id) }

  scope :users, where(:user_name.ne => IDLAST_USER_NAME)
  scope :users_pending, users.pending
  scope :users_pending_sorted_by_created_at, users_pending.order_by(created_at: -1)

  attr_accessible :img_id, :type, :approved, :approved_at, :uploaded_at

  field :img_id,      type: Integer
  field :type,        type: String
  field :approved,    type: Boolean, default: false
  field :approved_at, type: Time
  field :uploaded_at, type: Time,    default: ->{ Time.now }
  field :user_name,   type: String
  field :user_email,  type: String
  field :submitted,   type: Boolean, default: false

  validate :limit_num_of_pendings
  validate :validate_img_id_relevance
  validate :validate_uploaded_at
  validate :validate_approved_at

  validates_inclusion_of :type, in: [ 'vector', 'illustration', 'photo' ],
                          message: I18n.t(:chose_proper_pioneer_type)
  validates_numericality_of :img_id, greater_than: 140000000, less_than: 400000000,
                            message: I18n.t(:img_id_validation)
  validates_uniqueness_of :img_id

  voteable self, up: +1, down: -1
  voteable User, up: +1, down: -1

  def masked_id
    self.img_id.to_s[0...-3] << '***'
  end

  def predict_approved_at
    return nil if self.type != 'vector'

    # this method implements simple y=kx+b expression
    last = Pioneer.approved_vectors_sorted_by_img_id.first
    x1 = last.img_id
    y1 = last.approved_at.to_i

    first = Pioneer.approved_vectors_sorted_by_img_id.skip(400).first
    x2 = first.img_id
    y2 = first.approved_at.to_i

    k = (y2 - y1).to_f / (x2 - x1).to_f
    b = y1 - k * x1

    predict_utc_timestamp = k * self.img_id + b

    return Time.at(predict_utc_timestamp)
  end

  def uploaded_at_formatted
    return I18n.t(:unavailable) if self.user_name == IDLAST_USER_NAME
    self.uploaded_at.to_s(:short_datetime)
  end

  def approved_at_formatted
    self.approved_at.to_s(:short_datetime)
  end

  def predict_approved_at_formatted
    self.predict_approved_at.to_s(:short_datetime)
  end

  def on_the_road
    return I18n.t(:unavailable) if self.user_name == IDLAST_USER_NAME
    return I18n.t(:unavailable) if !self.approved
    substraction = self.approved_at - self.uploaded_at
    return I18n.t(:unavailable) if substraction <= 0
    road_hash = time_length(substraction)
    return "#{road_hash[:days]} #{I18n.t(:on_the_road_days)} #{road_hash[:hours]} #{I18n.t(:on_the_road_hours)} #{road_hash[:minutes]} #{I18n.t(:on_the_road_minutes)}"
  end

  def works_before_approval
    last_approved = Pioneer.last_approved_of_type(self.type).first
    return self.img_id - last_approved.img_id
  end

  def probably_approved?
    return false if self.approved
    last_approved = Pioneer.last_approved_of_type(self.type).first
    return true if self.img_id < last_approved.img_id
    return false
  end

  def pending?
    !self.approved?
  end

  def share_text
    substraction = self.approved_at - self.uploaded_at
    return nil if substraction <= 0
    road_hash = time_length(substraction)
    "#{self.masked_id} #{I18n.t(self.type)}<br />#{self.uploaded_at_formatted} - #{self.approved_at_formatted}<br />#{I18n.t(:on_the_road)}#{road_hash[:days]} #{I18n.t(:on_the_road_days)} #{road_hash[:hours]} #{I18n.t(:on_the_road_hours)}<br />#{I18n.t(:generated_by_idlast)}"
  end

  def voteble?
   return true if self.approved && (self.approved_at > 1.day.ago)
   false
  end

  private

  def limit_num_of_pendings
    pendings = self.user.pioneers.pendings_of_type(self.type)
    for pending in pendings do
      return true if pending.id == self.id
    end

    if pendings.length >= 1
      errors.add(:base, "You already have #{self.type} pending item")
    end

  end

  def mask_id
    self.img_id = (self.img_id.to_s[0...-3] + '000').to_i
  end

  def time_length seconds
    days = (seconds / 1.day).floor
    seconds -= days.days
    hours = (seconds / 1.hour).floor
    seconds -= hours.hours
    minutes = (seconds / 1.minute).floor
    seconds -= minutes.minutes
    { days: days, hours: hours, minutes: minutes, seconds: seconds }
  end

  #
  # Custom validations
  #

  def validate_img_id_relevance
    # img_id is relevant if it is greater than 10th last approved
    # of the same type
    tenth = Pioneer.approved_of_type_sorted_by_img_id(self.type).skip(10).first
    if tenth.img_id > self.img_id
      errors.add(:img_id, I18n.t(:img_id_not_relevant))
    end
  end

  def validate_uploaded_at
    # uploaded_at timestamp should be presented for all users
    # except IDLast.com user. It is the main reason
    # why I coudn't define uploaded_at field as not nil and use
    # before_save
    if !self.uploaded_at
      self.uploaded_at = Time.now # to render form properly
      errors.add(:uploaded_at, I18n.t(:uploaded_at_should_be_presented))
      return
    end

    # uploaded_at also should be in the past
    if self.uploaded_at >= DateTime.now
      errors.add(:uploaded_at, I18n.t(:uploaded_at_should_be_in_the_past))
    end
  end

  def validate_approved_at
    # if flag approved is true, approved_at should be presented
    if self.approved? && !self.approved_at
      self.approved_at = DateTime.now
      errors.add(:approved_at, I18n.t(:approved_at_should_be_presented))
      return
    end

    # approved_at also should be in the past
    if self.approved? && self.approved_at && (self.approved_at >= DateTime.now)
      errors.add(:approved_at, I18n.t(:approved_at_should_be_in_the_past))
      return
    end

    # approved_at should be greater than uploaded_at
    if self.approved? && self.approved_at && (self.approved_at <= self.uploaded_at)
      errors.add(:approved_at, I18n.t(:approved_at_should_be_greater_than_uploaded_at))
    end
  end

end

app/controllers/admin/pioneers_controller.rb
class Admin::PioneersController < Admin::AdminController

  def index
    @title = "All pioneers"
    @pioneers = Pioneer.approved_sorted_by_img_id.paginate(page: params[:page], per_page: 20)
    authorize! :index, @pioneers
  end

  def destroy
    @pioneer = Pioneer.find(params[:id])
    @pioneer.destroy
    redirect_to(request.referer)
  end


end

app/controllers/pioneers_controller.rb
class PioneersController < ApplicationController

  load_and_authorize_resource

  def index
    @title = t(:my_pioneers)
    @pioneers = current_user.pioneers.approved_sorted_by_img_id.paginate(page: params[:page], per_page: 10)
    @pendings = current_user.pioneers.pending
  end

  def statistics
    @title = t(:statistics)
  end

  def vectors
    @title = t(:vectors)
    @pioneers = Pioneer.approved_vectors_sorted_by_img_id.paginate(page: params[:page], per_page: 10)
  end

  def illustrations
    @title = t(:illustrations)
    @pioneers = Pioneer.approved_illustrations_sorted_by_img_id.paginate(page: params[:page], per_page: 10)
  end

  def photos
    @title = t(:photos)
    @pioneers = Pioneer.approved_photos_sorted_by_img_id.paginate(page: params[:page], per_page: 10)
  end

  def new
    @title = t(:new_pioneer)
    @pioneer = current_user.pioneers.new
  end

  def create
    @pioneer = current_user.pioneers.new(params[:pioneer])
    @pioneer.user_name = current_user.name
    @pioneer.user_email = current_user.email
    if @pioneer.save
      redirect_to(pioneers_path, notice: t(:pioneer_created_msg))
    else
      render action: "new"
    end
  end

  def edit
    @title = t(:edit_pioneer)
    @pioneer = Pioneer.find(params[:id])
  end

  def update
    @pioneer = Pioneer.find(params[:id])

    if @pioneer.update_attributes(params[:pioneer])
      redirect_to(pioneers_path, notice: t(:pioneer_updated_msg))
    else
      render action: "edit"
    end
  end

  def destroy
    @pioneer = Pioneer.find(params[:id])
    @pioneer.destroy
    redirect_to(pioneers_url)
  end

  def vote_up
    @pioneer = Pioneer.find(params[:id])
    @pioneer.vote(voter: current_user, value: :up) if @pioneer.voteble?
    respond_to do |format|
      format.js
    end
  end

  def vote_down
    @pioneer = Pioneer.find(params[:id])
    @pioneer.vote(voter: current_user, value: :down) if @pioneer.voteble?
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/admin/pioneers_helper.rb
module Admin::PioneersHelper
end

app/views/pioneers/_alert.html.erb
<div class="alert">
  <%= t(:idlast_email_notifications_alert).html_safe %>
  <%= link_to t(:more), article_path(Article.find('51cca75dd2b609330b0000e1')) %>
</div>

app/views/pioneers/_form.html.erb
<%= form_for(@pioneer) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <fieldset>

  <legend><%= @title %></legend>

    <%= f.label t(:pioneer_id) %>
    <%= f.text_field :img_id %>

	<br />

	<label class="radio">
	  <% if current_user.can_add_pioneer?('vector') %>
	    <input type="radio" name="pioneer[type]" id="vector" value="vector">
		<%= t(:vector) %>
	  <% else %>
	    <input type="radio" name="pioneer[type]" id="vector" value="vector" disabled>
	  <%= t(:vector) %> <span class="muted"><%= t(:one_pioneer_type_limit_notification) %></span>
	  <% end %>
	</label>
	<label class="radio">
	  <% if current_user.can_add_pioneer?('illustration') %>
	    <input type="radio" name="pioneer[type]" id="illustration" value="illustration">
	  <%= t(:illustration) %>
	  <% else %>
	    <input type="radio" name="pioneer[type]" id="illustration" value="illustration" disabled>
		<%= t(:illustration) %> <span class="muted"><%= t(:one_pioneer_type_limit_notification) %></span>
	  <% end %>
	</label>
	<label class="radio">
	  <% if current_user.can_add_pioneer?('photo') %>
	    <input type="radio" name="pioneer[type]" id="photo" value="photo">
		<%= t(:photo) %>
	  <% else %>
	    <input type="radio" name="pioneer[type]" id="photo" value="photo" disabled>
		<%= t(:photo) %> <span class="muted"><%= t(:one_pioneer_type_limit_notification) %></span>
	  <% end %>
	</label>

	<br />

	<%= f.label t(:uploaded_at) %>
	<div class="input-append">
      <%= f.text_field :uploaded_at, value: @pioneer.uploaded_at.strftime('%Y-%m-%d %H:%M') %>
	  <span class="add-on"><i class="icon-time"></i></span>
	</div>

	<br />

    <label class="checkbox">
	  <%= f.check_box :approved %> <%= t(:is_approved) %>
    </label>

	<div class="approved_date_container" style="display:none;">
	<br />
	<%= f.label t(:approved_at) %>
	<div class="input-append">
	  <% if @pioneer.approved_at %>
        <%= f.text_field :approved_at, value: @pioneer.approved_at.strftime('%Y-%m-%d %H:%M') %>
	  <% else %>
        <%= f.text_field :approved_at %>
	  <% end %>
	  <span class="add-on"><i class="icon-time"></i></span>
	</div>
	</div>

	<br />

    <button type="submit" class="btn"><%= t(:save) %></button>

  </fieldset>

<% end %>

app/views/pioneers/_pioneers.html.erb
<%= render 'alert' %>

<% if @pioneers.length > 0 %>

<table class="table table-striped">
<% @pioneers.each do |pioneer| %>
  <tr>
	<td>
	  <p># <%= pioneer.masked_id %></p>
	</td>
	<td>
	  <p><%= pioneer.approved_at_formatted %>
	    <br /><small class="muted"><%= t(:uploaded_at_short) %><%= pioneer.uploaded_at_formatted %></small>
		<br /><small class="muted"><%= t(:on_the_road) %><%= pioneer.on_the_road %></small>
	  </p>
	</td>
	<td>
	  <%= render 'vote', pioneer: pioneer %>
	</td>
	<td>
	  <p>
		<%= gravatar_image_tag(
			 pioneer.user_email,
			 alt: pioneer.user_name,
		     class: 'gravatar',
		     gravatar: { size: 25 }) %>
		<%= pioneer.user_name %>
		<sup> <%= pioneer.user.votes_point %></sup>
	  </p>
	</td>
  </tr>
<% end %>
</table>
<%= will_paginate %>

<% else %>

<p><%= t(:no_pioneers) %> <%= link_to t(:add_new_pioneer), new_pioneer_path %></p>

<% end %>

app/views/pioneers/_priv_pioneers.html.erb
<% if pioneers.length > 0 %>
<h3><%= title %></h3>
<table class="table table-striped">
<% pioneers.each do |pioneer| %>
  <% if pioneer.probably_approved? %>
  <tr class="warning">
  <% else %>
  <tr>
  <% end %>
	<td>
	  <p>
		# <%= pioneer.img_id %>
		<% if pioneer.pending? && !pioneer.probably_approved? %>
		  <br />
		  <small>
			<%= t(:works_before_approval) %><%= pioneer.works_before_approval %>
		  </small>
		<% end %>
		<% if pioneer.approved? %>
		  <br />
		  <%= link_to '#',
			  :'data-content' => pioneer.share_text,
		      :'data-html' => true,
		      class: 'pioneer-share-text btn btn-link btn-small' do %>
		    <%= t(:pioneer_text_for_forum) %>
		  <% end %>

		<% end %>
	  </p>
	</td>
	<td>
	  <p><%= t(pioneer.type) %></p>
	</td>
	<td>
	  <p>
	  <% if pioneer.approved? %>
	    <%= pioneer.approved_at_formatted %>
	  <% end %>
	  <% if pioneer.pending? and pioneer.type == 'vector' && !pioneer.probably_approved? %>
	  <span class="muted"><%= pioneer.predict_approved_at_formatted %></span>
	  <% end %>
	  <% if pioneer.probably_approved? %>
	    <span class="text-info"><%= t(:probably_approved) %></span>
	  <% end %>
      <br /><small class="muted"><%= t(:uploaded_at_short) %><%= pioneer.uploaded_at_formatted %></small>
	  <% if pioneer.approved? %>
	  <br /><small class="muted"><%= t(:on_the_road) %><%= pioneer.on_the_road %></small>
	  <% end %>
	  </p>
	</td>
	<td>
	  <% if pioneer.votes_point > 0 %>
	    <span class="text-success"><b>+<%= pioneer.votes_point %></b></span>
	  <% elsif pioneer.votes_point < 0 %>
		<span class="text-error"><b><%= pioneer.votes_point %></b></span>
	  <% else %>
	    <span class="muted"><b><%= pioneer.votes_point %></b></span>
	  <% end %>
	</td>
	<td>
      <%= link_to t(:edit), edit_pioneer_path(pioneer) %>
	</td>
	<td>
	  <%= link_to t(:delete), pioneer, {
		  confirm: t(:are_you_sure),
	      method: :delete,
	      class: 'text-error'} %>
	</td>
  </tr>
<% end %>
</table>
<% end %>

app/views/pioneers/_vote.html.erb
<div id="<%= "votes_#{pioneer.id}" %>">

  <% if current_user.voted?(pioneer) || !pioneer.voteble? %>
    <i style="visibility:hidden;" class="icon-arrow-up muted"></i>
  <% else %>
    <%= link_to vote_up_path(pioneer), remote: true do %>
      <i style="text-decoration:none;"  class="icon-arrow-up"></i>
    <% end %>
  <% end %>

  <% if pioneer.votes_point > 0 %>
    <span class="text-success"><b>+<%= pioneer.votes_point %></b></span>
  <% elsif pioneer.votes_point < 0 %>
	<span class="text-error"><b><%= pioneer.votes_point %></b></span>
  <% else %>
	<span class="muted"><b><%= pioneer.votes_point %></b></span>
  <% end %>

  <% if current_user.voted?(pioneer) || !pioneer.voteble? %>
	 <i style="visibility:hidden;" class="icon-arrow-down muted"></i>
  <% else %>
	<%= link_to vote_down_path(pioneer), remote: true do %>
      <i style="text-decoration:none;" class="icon-arrow-down"></i>
    <% end %>
  <% end %>

</div>

app/views/pioneers/edit.html.erb
<%= render 'form' %>

app/views/pioneers/illustrations.html.erb
<%= render 'pioneers' %>

app/views/pioneers/index.html.erb
<%= render('priv_pioneers', title: t(:pending_pioneers), pioneers: @pendings) %>
<%= render('priv_pioneers', title: t(:approved_pioneers), pioneers: @pioneers) %>

<%= will_paginate @pioneers %>

<% if @pendings.length == 0 and @pioneers.length == 0 %>
<p><%= t(:your_have_no_pioneers) %> <%= link_to t(:add_new_pioneer), new_pioneer_path %></p>
<% end %>

app/views/pioneers/new.html.erb
<% if current_user.can_add_pioneers? %>
  <%= render 'form' %>
<% else %>
  <div class="alert"><strong><%= t(:warning) %>:</strong> <%= t(:pending_pioneers_limit_notification) %> </div>
<% end %>

app/views/pioneers/photos.html.erb
<%= render 'pioneers' %>

app/views/pioneers/statistics.html.erb
<center>
  <p><%= t(:may_vectors_plot) %> </p>
</center>
<%= link_to '/assets/vectors.png', {target: '_blank', title: t(:to_open_img) } do %>
  <%= image_tag('vectors.png') %>
<% end %>

app/views/pioneers/vectors.html.erb
<%= render 'pioneers' %>

app/views/pioneers/vote_down.js.erb
$('<%= "#votes_#{@pioneer.id}" %>').html("<%= escape_javascript(render('pioneers/vote', pioneer: @pioneer)) %>")

app/views/pioneers/vote_up.js.erb
$('<%= "#votes_#{@pioneer.id}" %>').html("<%= escape_javascript(render('pioneers/vote', pioneer: @pioneer)) %>")