config/routes.rb
Stui::Application.routes.draw do

  root to: 'pages#home'
  match 'about_us' => 'pages#about_us'

  match 'photos' => 'pioneers#photos'
  match 'vectors' => 'pioneers#vectors'
  match 'illustrations' => 'pioneers#illustrations'
  match 'statistics' => 'pioneers#statistics'

  match 'pioneers/:id/vote_up' => 'pioneers#vote_up', :as => :vote_up
  match 'pioneers/:id/vote_down' => 'pioneers#vote_down', :as => :vote_down

  resources :pioneers

  resources :articles do
    resources :comments
  end

  devise_for :users
  resources :users do
    member do
      put :update_pass
      put :change_article_notification
      put :change_timezone
    end
  end

  match 'admin' => redirect('/admin/users')
  namespace :admin do
    resources :users
    resources :articles
    resources :pioneers
    resources :pendings
  end

end

app/views/layouts/admin/_header.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to admin_path, class: "brand" do %>
	  <span style="color:red;">Admin Panel</span>
	  <% end %>
      <div class="container nav-collapse">
		<ul class="nav">
		  <%= li_link_to "Frontend", root_path %>
		</ul> <!-- ul class nav -->

		<ul class="nav pull-right">
		  <li><%= link_to "My profile", user_path(current_user) %></li>
		  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        </ul>

      </div><!--/.nav-collapse -->

    </div>
  </div>
</div>

app/views/layouts/admin/app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

  </head>
  <body>

	<%= render 'layouts/admin/header' %>

    <div class="container">

	  <!-- flash -->
	  <div class="row">
		<div class="span12">
		  <%= bootstrap_flash %>
		</div> <!-- span12 -->
	  </div> <!-- row -->
	  <!-- end flash -->

	<% if user_signed_in? %>
      <div class="row" style="margin-top:30px;">
		<div class="span3">
		  <%= render 'layouts/admin-navbar' %>
		</div><!--/span-->
        <div class="span9">
          <%# bootstrap_flash %>
          <%= yield %>
        </div><!--/span-->
	  </div><!-- /row -->
	<% elsif controller_name == 'articles' %>
	  <div class="row" style="margin-top:30px;">
		<div class="span3"></div>
		<div class="span9"><%= yield %></div>
	  </div> <!-- row -->
	<% else %>
    <%= yield %>
	<% end %>

	<%= render 'layouts/footer' %>

    </div> <!-- /container -->

    <!-- Javascripts
		 ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>