config/routes.rb
Stui::Application.routes.draw do

  root to: 'pages#home'
  match 'about_us' => 'pages#about_us'

  match 'photos' => 'pioneers#photos'
  match 'vectors' => 'pioneers#vectors'
  match 'illustrations' => 'pioneers#illustrations'
  match 'statistics' => 'pioneers#statistics'

  match 'pioneers/:id/vote_up' => 'pioneers#vote_up', :as => :vote_up
  match 'pioneers/:id/vote_down' => 'pioneers#vote_down', :as => :vote_down

  resources :pioneers

  resources :articles do
    resources :comments
  end

  devise_for :users
  resources :users do
    member do
      put :update_pass
      put :change_article_notification
      put :change_timezone
    end
  end

  match 'admin' => redirect('/admin/users')
  namespace :admin do
    resources :users
    resources :articles
    resources :pioneers
    resources :pendings
  end

end

app/views/layouts/_admin-navbar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
	<%= li_link_to "Users", admin_users_path %>
	<%= li_link_to "Pioneers", admin_pioneers_path %>
	<%= li_link_to "Pendings", admin_pendings_path %>
	<%= li_link_to "Articles", admin_articles_path %>
  </ul>
</div><!--/.well -->

app/views/layouts/_footer.html.erb
<footer style="margin-bottom:20px;">
  <hr>
  <center><p>&copy; 2013 IDLast. All rights reserved.</p></center>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to root_path, class: "brand" do %>
	  <span>IDLast
		<sup> <i>microstock.ru</i></sup>
	  </span>
	  <% end %>
      <div class="container nav-collapse">
		<ul class="nav">
		  <%= li_link_to t(:blog_h), articles_path %>
		  <%= li_link_to t(:about_us_h), about_us_path %>
		</ul> <!-- ul class nav -->
		<% if user_signed_in? %>
		<ul class="nav pull-right">
		  <% if current_user.timezone_presented? %>
		    <li><%= link_to Time.zone.to_s, '#' %></li>
		  <% end %>
		  <li><%= link_to t(:my_profile_h), user_path(current_user) %></li>
		  <li><%= link_to t(:sign_out), destroy_user_session_path, method: :delete %></li>
		<% else %>

        <ul class="nav pull-right">

		  <!--doesn't show signup btn at home page and at signup page -->
		  <% if (controller_name != 'pages' && action_name != 'home') && controller_name != 'registrations' %>
		  <li><div><%= link_to t(:sign_up), new_user_registration_path, class: "btn btn-success" %></div></li>
		  <% end %>

		  <!-- doesn't show divider at sigin/sigup/home pages -->
		  <% if controller_name != 'sessions' &&
			 controller_name != 'registrations' &&
			 (controller_name != 'pages' && action_name != 'home') %>
		  <li class="divider-vertical"></li>
		  <% end %>


		  <!-- doesn't show sigin btn at sigin page -->
		  <% if controller_name != 'sessions' %>
		  <li><div><%= link_to t(:sign_in), new_user_session_path, class: "btn" %></div></li>
		  <% end %>
        </ul>
		<% end %>
      </div><!--/.nav-collapse -->

    </div>
  </div>
</div>

app/views/layouts/_pioneer-navbar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
	<%= li_link_to t(:vectors), vectors_path %>
	<%= li_link_to t(:illustrations), illustrations_path %>
	<%= li_link_to t(:photos), photos_path %>
    <%= li_link_to t(:my_pioneers), pioneers_path  %>
	<% if can? :create, Pioneer.new %>
      <%= li_link_to t(:add_new_pioneer), new_pioneer_path  %>
	<% end %>
    <%= li_link_to t(:statistics), statistics_path  %>
  </ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title><%= title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
		<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
		<![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%# favicon_link_tag 'images/apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%# favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-40899693-1', 'idlast.com');
	  ga('send', 'pageview');

	</script>
  </head>
  <body>

	<%= render 'layouts/header' %>

    <div class="container">

	  <!-- flash -->
	  <div class="row">
		<div class="span12">
		  <%= bootstrap_flash %>
		</div> <!-- span12 -->
	  </div> <!-- row -->
	  <!-- end flash -->

	<% if user_signed_in? %>
      <div class="row" style="margin-top:30px;">
		<div class="span3">
		  <%= render 'layouts/pioneer-navbar' %>
		</div><!--/span-->
        <div class="span9">
          <%# bootstrap_flash %>
          <%= yield %>
        </div><!--/span-->
	  </div><!-- /row -->
	<% elsif controller_name == 'articles' or action_name == 'about_us' %>
	  <div class="row" style="margin-top:30px;">
		<div class="span3"></div>
		<div class="span9"><%= yield %></div>
	  </div> <!-- row -->
	<% else %>
    <%= yield %>
	<% end %>

	<%= render 'layouts/footer' %>

    </div> <!-- /container -->

    <!-- Javascripts
		 ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>